// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
export const mixerUrl = new URL('./mixer-module.wasm', import.meta.url)
export const meta = {
    "name": "noiseres",
    "filename": "noiseres",
    "version": "2.84.3",
    "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2",
    "library_list": [
        "/usr/share/faust/stdfaust.lib",
        "/usr/share/faust/noises.lib",
        "/usr/share/faust/filters.lib",
        "/usr/share/faust/basics.lib",
        "/usr/share/faust/maths.lib",
        "/usr/share/faust/envelopes.lib",
        "/usr/share/faust/platform.lib",
        "/usr/share/faust/signals.lib",
        "/usr/share/faust/routes.lib",
        "/usr/share/faust/oscillators.lib"
    ],
    "include_pathnames": [
        "/faust/user/inc0",
        "/share/faust",
        "/usr/local/share/faust",
        "/usr/share/faust",
        "."
    ],
    "size": 262380,
    "code": "uKwIAVQ8Hw==",
    "inputs": 0,
    "outputs": 2,
    "meta": [
        {
            "basics.lib/name": "Faust Basic Element Library"
        },
        {
            "basics.lib/version": "1.22.0"
        },
        {
            "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2"
        },
        {
            "envelopes.lib/adsr:author": "Yann Orlarey and Andrey Bundin"
        },
        {
            "envelopes.lib/author": "GRAME"
        },
        {
            "envelopes.lib/copyright": "GRAME"
        },
        {
            "envelopes.lib/license": "LGPL with exception"
        },
        {
            "envelopes.lib/name": "Faust Envelope Library"
        },
        {
            "envelopes.lib/version": "1.3.0"
        },
        {
            "filename": "noiseres"
        },
        {
            "filters.lib/fir:author": "Julius O. Smith III"
        },
        {
            "filters.lib/fir:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/fir:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/iir:author": "Julius O. Smith III"
        },
        {
            "filters.lib/iir:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/iir:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/lowpass0_highpass1": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/name": "Faust Filters Library"
        },
        {
            "filters.lib/resonbp:author": "Julius O. Smith III"
        },
        {
            "filters.lib/resonbp:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/resonbp:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/svf:author": "Oleg Nesterov"
        },
        {
            "filters.lib/svf:copyright": "Copyright (C) 2020 Oleg Nesterov <oleg@redhat.com>"
        },
        {
            "filters.lib/svf:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf2:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf2:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf2:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf2s:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf2s:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf2s:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/version": "1.7.1"
        },
        {
            "maths.lib/author": "GRAME"
        },
        {
            "maths.lib/copyright": "GRAME"
        },
        {
            "maths.lib/license": "LGPL with exception"
        },
        {
            "maths.lib/name": "Faust Math Library"
        },
        {
            "maths.lib/version": "2.9.0"
        },
        {
            "name": "noiseres"
        },
        {
            "noises.lib/name": "Faust Noise Generator Library"
        },
        {
            "noises.lib/version": "1.5.0"
        },
        {
            "oscillators.lib/name": "Faust Oscillator Library"
        },
        {
            "oscillators.lib/version": "1.7.0"
        },
        {
            "platform.lib/name": "Generic Platform Library"
        },
        {
            "platform.lib/version": "1.3.0"
        },
        {
            "routes.lib/name": "Faust Signal Routing Library"
        },
        {
            "routes.lib/version": "1.2.0"
        },
        {
            "signals.lib/name": "Faust Signal Routing Library"
        },
        {
            "signals.lib/version": "1.6.0"
        }
    ],
    "ui": [
        {
            "type": "vgroup",
            "label": "noiseres",
            "items": [
                {
                    "type": "hslider",
                    "label": "a",
                    "varname": "fHslider6",
                    "shortname": "a",
                    "address": "/noiseres/a",
                    "index": 262276,
                    "init": 500,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "d",
                    "varname": "fHslider8",
                    "shortname": "d",
                    "address": "/noiseres/d",
                    "index": 262284,
                    "init": 0,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "fila",
                    "varname": "fHslider2",
                    "shortname": "fila",
                    "address": "/noiseres/fila",
                    "index": 262188,
                    "init": 500,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "fild",
                    "varname": "fHslider4",
                    "shortname": "fild",
                    "address": "/noiseres/fild",
                    "index": 262216,
                    "init": 0,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "filr",
                    "varname": "fHslider5",
                    "shortname": "filr",
                    "address": "/noiseres/filr",
                    "index": 262220,
                    "init": 800,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "fils",
                    "varname": "fHslider3",
                    "shortname": "fils",
                    "address": "/noiseres/fils",
                    "index": 262212,
                    "init": 1,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "freq",
                    "varname": "fHslider0",
                    "shortname": "freq",
                    "address": "/noiseres/freq",
                    "index": 262144,
                    "init": 440,
                    "min": 20,
                    "max": 20000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "gain",
                    "varname": "fHslider1",
                    "shortname": "gain",
                    "address": "/noiseres/gain",
                    "index": 262148,
                    "init": 0.75,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "button",
                    "label": "gate",
                    "varname": "fButton0",
                    "shortname": "gate",
                    "address": "/noiseres/gate",
                    "index": 262192
                },
                {
                    "type": "hslider",
                    "label": "lagtime",
                    "varname": "fHslider11",
                    "shortname": "lagtime",
                    "address": "/noiseres/lagtime",
                    "index": 262296,
                    "init": 0,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "pan",
                    "varname": "fHslider13",
                    "shortname": "pan",
                    "address": "/noiseres/pan",
                    "index": 262332,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "r",
                    "varname": "fHslider9",
                    "shortname": "r",
                    "address": "/noiseres/r",
                    "index": 262288,
                    "init": 800,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "s",
                    "varname": "fHslider7",
                    "shortname": "s",
                    "address": "/noiseres/s",
                    "index": 262280,
                    "init": 1,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "tremelorate",
                    "varname": "fHslider12",
                    "shortname": "tremelorate",
                    "address": "/noiseres/tremelorate",
                    "index": 262312,
                    "init": 4,
                    "min": 0.1,
                    "max": 20,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "tremolo",
                    "varname": "fHslider10",
                    "shortname": "tremolo",
                    "address": "/noiseres/tremolo",
                    "index": 262292,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                }
            ]
        }
    ]
}
