// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
export const mixerUrl = new URL('./mixer-module.wasm', import.meta.url)
export const meta = {
    "name": "hihat",
    "filename": "hihat",
    "version": "2.84.3",
    "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2",
    "library_list": [
        "/usr/share/faust/stdfaust.lib",
        "/usr/share/faust/filters.lib",
        "/usr/share/faust/oscillators.lib",
        "/usr/share/faust/maths.lib",
        "/usr/share/faust/platform.lib",
        "/usr/share/faust/signals.lib",
        "/usr/share/faust/routes.lib",
        "/usr/share/faust/noises.lib",
        "/usr/share/faust/envelopes.lib",
        "/usr/share/faust/basics.lib"
    ],
    "include_pathnames": [
        "/faust/user/inc0",
        "/share/faust",
        "/usr/local/share/faust",
        "/usr/share/faust",
        "."
    ],
    "size": 49372,
    "code": "ILIJAVQ8Hw==",
    "inputs": 0,
    "outputs": 2,
    "meta": [
        {
            "basics.lib/name": "Faust Basic Element Library"
        },
        {
            "basics.lib/version": "1.22.0"
        },
        {
            "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2"
        },
        {
            "envelopes.lib/adsr:author": "Yann Orlarey and Andrey Bundin"
        },
        {
            "envelopes.lib/author": "GRAME"
        },
        {
            "envelopes.lib/copyright": "GRAME"
        },
        {
            "envelopes.lib/license": "LGPL with exception"
        },
        {
            "envelopes.lib/name": "Faust Envelope Library"
        },
        {
            "envelopes.lib/version": "1.3.0"
        },
        {
            "filename": "hihat"
        },
        {
            "filters.lib/lowpass0_highpass1": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/name": "Faust Filters Library"
        },
        {
            "filters.lib/svf:author": "Oleg Nesterov"
        },
        {
            "filters.lib/svf:copyright": "Copyright (C) 2020 Oleg Nesterov <oleg@redhat.com>"
        },
        {
            "filters.lib/svf:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/version": "1.7.1"
        },
        {
            "maths.lib/author": "GRAME"
        },
        {
            "maths.lib/copyright": "GRAME"
        },
        {
            "maths.lib/license": "LGPL with exception"
        },
        {
            "maths.lib/name": "Faust Math Library"
        },
        {
            "maths.lib/version": "2.9.0"
        },
        {
            "name": "hihat"
        },
        {
            "noises.lib/name": "Faust Noise Generator Library"
        },
        {
            "noises.lib/version": "1.5.0"
        },
        {
            "oscillators.lib/lf_sawpos:author": "Bart Brouns, revised by Stéphane Letz"
        },
        {
            "oscillators.lib/lf_sawpos:licence": "STK-4.3"
        },
        {
            "oscillators.lib/name": "Faust Oscillator Library"
        },
        {
            "oscillators.lib/sawN:author": "Julius O. Smith III"
        },
        {
            "oscillators.lib/sawN:license": "STK-4.3"
        },
        {
            "oscillators.lib/version": "1.7.0"
        },
        {
            "platform.lib/name": "Generic Platform Library"
        },
        {
            "platform.lib/version": "1.3.0"
        },
        {
            "routes.lib/name": "Faust Signal Routing Library"
        },
        {
            "routes.lib/version": "1.2.0"
        },
        {
            "signals.lib/name": "Faust Signal Routing Library"
        },
        {
            "signals.lib/version": "1.6.0"
        }
    ],
    "ui": [
        {
            "type": "vgroup",
            "label": "hihat",
            "items": [
                {
                    "type": "hslider",
                    "label": "a",
                    "varname": "fHslider4",
                    "shortname": "a",
                    "address": "/hihat/a",
                    "index": 49312,
                    "init": 1,
                    "min": 0,
                    "max": 500,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "cutoff",
                    "varname": "fHslider3",
                    "shortname": "cutoff",
                    "address": "/hihat/cutoff",
                    "index": 49264,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "d",
                    "varname": "fHslider6",
                    "shortname": "d",
                    "address": "/hihat/d",
                    "index": 49340,
                    "init": 80,
                    "min": 0,
                    "max": 2000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "freq",
                    "varname": "fHslider1",
                    "shortname": "freq",
                    "address": "/hihat/freq",
                    "index": 4,
                    "init": 205,
                    "min": 20,
                    "max": 2000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "gain",
                    "varname": "fHslider0",
                    "shortname": "gain",
                    "address": "/hihat/gain",
                    "index": 0,
                    "init": 1,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "button",
                    "label": "gate",
                    "varname": "fButton0",
                    "shortname": "gate",
                    "address": "/hihat/gate",
                    "index": 49316
                },
                {
                    "type": "hslider",
                    "label": "lagtime",
                    "varname": "fHslider9",
                    "shortname": "lagtime",
                    "address": "/hihat/lagtime",
                    "index": 49360,
                    "init": 0,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "metal",
                    "varname": "fHslider2",
                    "shortname": "metal",
                    "address": "/hihat/metal",
                    "index": 8,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "pan",
                    "varname": "fHslider8",
                    "shortname": "pan",
                    "address": "/hihat/pan",
                    "index": 49356,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "r",
                    "varname": "fHslider7",
                    "shortname": "r",
                    "address": "/hihat/r",
                    "index": 49344,
                    "init": 20,
                    "min": 0,
                    "max": 1000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "s",
                    "varname": "fHslider5",
                    "shortname": "s",
                    "address": "/hihat/s",
                    "index": 49336,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                }
            ]
        }
    ]
}
