// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
export const mixerUrl = new URL('./mixer-module.wasm', import.meta.url)
export const meta = {
    "name": "fm",
    "filename": "fm",
    "version": "2.84.3",
    "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2",
    "library_list": [
        "/usr/share/faust/stdfaust.lib",
        "/usr/share/faust/oscillators.lib",
        "/usr/share/faust/basics.lib",
        "/usr/share/faust/signals.lib",
        "/usr/share/faust/maths.lib",
        "/usr/share/faust/platform.lib",
        "/usr/share/faust/envelopes.lib",
        "/usr/share/faust/filters.lib"
    ],
    "include_pathnames": [
        "/faust/user/inc0",
        "/share/faust",
        "/usr/local/share/faust",
        "/usr/share/faust",
        "."
    ],
    "size": 262592,
    "code": "oBQ5AVQ8Hw==",
    "inputs": 0,
    "outputs": 2,
    "meta": [
        {
            "basics.lib/name": "Faust Basic Element Library"
        },
        {
            "basics.lib/version": "1.22.0"
        },
        {
            "compile_options": "-lang wasm-e -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2"
        },
        {
            "envelopes.lib/adsr:author": "Yann Orlarey and Andrey Bundin"
        },
        {
            "envelopes.lib/author": "GRAME"
        },
        {
            "envelopes.lib/copyright": "GRAME"
        },
        {
            "envelopes.lib/license": "LGPL with exception"
        },
        {
            "envelopes.lib/name": "Faust Envelope Library"
        },
        {
            "envelopes.lib/version": "1.3.0"
        },
        {
            "filename": "fm"
        },
        {
            "filters.lib/bandpass0_bandstop1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/bandpass0_bandstop1:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/bandpass0_bandstop1:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/bandpass:author": "Julius O. Smith III"
        },
        {
            "filters.lib/bandpass:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/bandpass:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/fir:author": "Julius O. Smith III"
        },
        {
            "filters.lib/fir:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/fir:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/highpass:author": "Julius O. Smith III"
        },
        {
            "filters.lib/highpass:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/iir:author": "Julius O. Smith III"
        },
        {
            "filters.lib/iir:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/iir:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/lowpass0_highpass1": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/lowpass0_highpass1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/lowpass:author": "Julius O. Smith III"
        },
        {
            "filters.lib/lowpass:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/lowpass:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/name": "Faust Filters Library"
        },
        {
            "filters.lib/nlf2:author": "Julius O. Smith III"
        },
        {
            "filters.lib/nlf2:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/nlf2:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf2:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf2:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf2:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf2s:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf2s:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf2s:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf2sb:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf2sb:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf2sb:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/version": "1.7.1"
        },
        {
            "maths.lib/author": "GRAME"
        },
        {
            "maths.lib/copyright": "GRAME"
        },
        {
            "maths.lib/license": "LGPL with exception"
        },
        {
            "maths.lib/name": "Faust Math Library"
        },
        {
            "maths.lib/version": "2.9.0"
        },
        {
            "name": "fm"
        },
        {
            "oscillators.lib/name": "Faust Oscillator Library"
        },
        {
            "oscillators.lib/version": "1.7.0"
        },
        {
            "platform.lib/name": "Generic Platform Library"
        },
        {
            "platform.lib/version": "1.3.0"
        },
        {
            "signals.lib/name": "Faust Signal Routing Library"
        },
        {
            "signals.lib/version": "1.6.0"
        }
    ],
    "ui": [
        {
            "type": "vgroup",
            "label": "fm",
            "items": [
                {
                    "type": "hslider",
                    "label": "a",
                    "varname": "fHslider12",
                    "shortname": "a",
                    "address": "/fm/a",
                    "index": 262296,
                    "init": 10,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "amp",
                    "varname": "fHslider3",
                    "shortname": "amp",
                    "address": "/fm/amp",
                    "index": 262156,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "bpf",
                    "varname": "fHslider0",
                    "shortname": "bpf",
                    "address": "/fm/bpf",
                    "index": 262144,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "d",
                    "varname": "fHslider14",
                    "shortname": "d",
                    "address": "/fm/d",
                    "index": 262304,
                    "init": 100,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "button",
                    "label": "gate",
                    "varname": "fButton0",
                    "shortname": "gate",
                    "address": "/fm/gate",
                    "index": 262160
                },
                {
                    "type": "hslider",
                    "label": "harm",
                    "varname": "fHslider7",
                    "shortname": "harm",
                    "address": "/fm/harm",
                    "index": 262236,
                    "init": 2,
                    "min": 0.1,
                    "max": 16,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "hpf",
                    "varname": "fHslider1",
                    "shortname": "hpf",
                    "address": "/fm/hpf",
                    "index": 262148,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "lag",
                    "varname": "fHslider4",
                    "shortname": "lag",
                    "address": "/fm/lag",
                    "index": 262192,
                    "init": 0,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "lpf",
                    "varname": "fHslider2",
                    "shortname": "lpf",
                    "address": "/fm/lpf",
                    "index": 262152,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "moda",
                    "varname": "fHslider8",
                    "shortname": "moda",
                    "address": "/fm/moda",
                    "index": 262248,
                    "init": 0,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "modd",
                    "varname": "fHslider10",
                    "shortname": "modd",
                    "address": "/fm/modd",
                    "index": 262264,
                    "init": 100,
                    "min": 0,
                    "max": 5000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "modi",
                    "varname": "fHslider6",
                    "shortname": "modi",
                    "address": "/fm/modi",
                    "index": 262220,
                    "init": 3,
                    "min": 0,
                    "max": 20,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "modr",
                    "varname": "fHslider11",
                    "shortname": "modr",
                    "address": "/fm/modr",
                    "index": 262268,
                    "init": 500,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "mods",
                    "varname": "fHslider9",
                    "shortname": "mods",
                    "address": "/fm/mods",
                    "index": 262260,
                    "init": 1,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "n",
                    "varname": "fHslider5",
                    "shortname": "n",
                    "address": "/fm/n",
                    "index": 262208,
                    "init": 60,
                    "min": 0,
                    "max": 127,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "pan",
                    "varname": "fHslider16",
                    "shortname": "pan",
                    "address": "/fm/pan",
                    "index": 262312,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "r",
                    "varname": "fHslider15",
                    "shortname": "r",
                    "address": "/fm/r",
                    "index": 262308,
                    "init": 300,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "res",
                    "varname": "fHslider17",
                    "shortname": "res",
                    "address": "/fm/res",
                    "index": 262388,
                    "init": 1,
                    "min": 0.01,
                    "max": 100,
                    "step": 0.01
                },
                {
                    "type": "hslider",
                    "label": "s",
                    "varname": "fHslider13",
                    "shortname": "s",
                    "address": "/fm/s",
                    "index": 262300,
                    "init": 0.7,
                    "min": 0,
                    "max": 1,
                    "step": 0.01
                }
            ]
        }
    ]
}
