// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
export const meta = {
    "name": "distortion",
    "filename": "distortion",
    "version": "2.84.3",
    "compile_options": "-lang wasm-i -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2",
    "library_list": [
        "/usr/share/faust/stdfaust.lib",
        "/usr/share/faust/signals.lib",
        "/usr/share/faust/maths.lib",
        "/usr/share/faust/platform.lib",
        "/usr/share/faust/filters.lib"
    ],
    "include_pathnames": [
        "/faust/user/inc0",
        "/share/faust",
        "/usr/local/share/faust",
        "/usr/share/faust",
        "."
    ],
    "size": 88,
    "code": "VDwf",
    "inputs": 2,
    "outputs": 2,
    "meta": [
        {
            "compile_options": "-lang wasm-i -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2"
        },
        {
            "filename": "distortion"
        },
        {
            "filters.lib/lowpass0_highpass1": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/lowpass0_highpass1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/lowpass:author": "Julius O. Smith III"
        },
        {
            "filters.lib/lowpass:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/lowpass:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/name": "Faust Filters Library"
        },
        {
            "filters.lib/tf1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf1:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf1:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf1s:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf1s:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf1s:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/version": "1.7.1"
        },
        {
            "maths.lib/author": "GRAME"
        },
        {
            "maths.lib/copyright": "GRAME"
        },
        {
            "maths.lib/license": "LGPL with exception"
        },
        {
            "maths.lib/name": "Faust Math Library"
        },
        {
            "maths.lib/version": "2.9.0"
        },
        {
            "name": "distortion"
        },
        {
            "platform.lib/name": "Generic Platform Library"
        },
        {
            "platform.lib/version": "1.3.0"
        },
        {
            "signals.lib/name": "Faust Signal Routing Library"
        },
        {
            "signals.lib/version": "1.6.0"
        }
    ],
    "ui": [
        {
            "type": "vgroup",
            "label": "distortion",
            "items": [
                {
                    "type": "hslider",
                    "label": "drive",
                    "varname": "fHslider3",
                    "shortname": "drive",
                    "address": "/distortion/drive",
                    "index": 44,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "lagtime",
                    "varname": "fHslider1",
                    "shortname": "lagtime",
                    "address": "/distortion/lagtime",
                    "index": 16,
                    "init": 0,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "mix",
                    "varname": "fHslider0",
                    "shortname": "mix",
                    "address": "/distortion/mix",
                    "index": 0,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "tone",
                    "varname": "fHslider2",
                    "shortname": "tone",
                    "address": "/distortion/tone",
                    "index": 32,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                }
            ]
        }
    ]
}
