// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
export const meta = {
    "name": "tape",
    "filename": "tape",
    "version": "2.84.3",
    "compile_options": "-lang wasm-i -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2",
    "library_list": [
        "/usr/share/faust/stdfaust.lib",
        "/usr/share/faust/signals.lib",
        "/usr/share/faust/maths.lib",
        "/usr/share/faust/platform.lib",
        "/usr/share/faust/noises.lib",
        "/usr/share/faust/filters.lib",
        "/usr/share/faust/delays.lib",
        "/usr/share/faust/oscillators.lib"
    ],
    "include_pathnames": [
        "/faust/user/inc0",
        "/share/faust",
        "/usr/local/share/faust",
        "/usr/share/faust",
        "."
    ],
    "size": 16548,
    "code": "GPj7",
    "inputs": 2,
    "outputs": 2,
    "meta": [
        {
            "compile_options": "-lang wasm-i -fpga-mem-th 4 -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 2"
        },
        {
            "delays.lib/name": "Faust Delay Library"
        },
        {
            "delays.lib/version": "1.2.0"
        },
        {
            "filename": "tape"
        },
        {
            "filters.lib/highpass:author": "Julius O. Smith III"
        },
        {
            "filters.lib/highpass:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/lowpass0_highpass1": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/lowpass0_highpass1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/name": "Faust Filters Library"
        },
        {
            "filters.lib/tf1:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf1:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf1:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/tf1s:author": "Julius O. Smith III"
        },
        {
            "filters.lib/tf1s:copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>"
        },
        {
            "filters.lib/tf1s:license": "MIT-style STK-4.3 license"
        },
        {
            "filters.lib/version": "1.7.1"
        },
        {
            "maths.lib/author": "GRAME"
        },
        {
            "maths.lib/copyright": "GRAME"
        },
        {
            "maths.lib/license": "LGPL with exception"
        },
        {
            "maths.lib/name": "Faust Math Library"
        },
        {
            "maths.lib/version": "2.9.0"
        },
        {
            "name": "tape"
        },
        {
            "noises.lib/name": "Faust Noise Generator Library"
        },
        {
            "noises.lib/version": "1.5.0"
        },
        {
            "oscillators.lib/lf_sawpos:author": "Bart Brouns, revised by Stéphane Letz"
        },
        {
            "oscillators.lib/lf_sawpos:licence": "STK-4.3"
        },
        {
            "oscillators.lib/lf_triangle:author": "Bart Brouns"
        },
        {
            "oscillators.lib/lf_triangle:licence": "STK-4.3"
        },
        {
            "oscillators.lib/name": "Faust Oscillator Library"
        },
        {
            "oscillators.lib/saw1:author": "Bart Brouns"
        },
        {
            "oscillators.lib/saw1:licence": "STK-4.3"
        },
        {
            "oscillators.lib/version": "1.7.0"
        },
        {
            "platform.lib/name": "Generic Platform Library"
        },
        {
            "platform.lib/version": "1.3.0"
        },
        {
            "signals.lib/name": "Faust Signal Routing Library"
        },
        {
            "signals.lib/version": "1.6.0"
        }
    ],
    "ui": [
        {
            "type": "vgroup",
            "label": "tape",
            "items": [
                {
                    "type": "hslider",
                    "label": "flutter",
                    "varname": "fHslider4",
                    "shortname": "flutter",
                    "address": "/tape/flutter",
                    "index": 8268,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "hiss",
                    "varname": "fHslider5",
                    "shortname": "hiss",
                    "address": "/tape/hiss",
                    "index": 8312,
                    "init": 0.5,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "lagtime",
                    "varname": "fHslider1",
                    "shortname": "lagtime",
                    "address": "/tape/lagtime",
                    "index": 16,
                    "init": 0,
                    "min": 0,
                    "max": 10000,
                    "step": 1
                },
                {
                    "type": "hslider",
                    "label": "mix",
                    "varname": "fHslider0",
                    "shortname": "mix",
                    "address": "/tape/mix",
                    "index": 0,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "sat",
                    "varname": "fHslider2",
                    "shortname": "sat",
                    "address": "/tape/sat",
                    "index": 36,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "wow",
                    "varname": "fHslider3",
                    "shortname": "wow",
                    "address": "/tape/wow",
                    "index": 8244,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                },
                {
                    "type": "hslider",
                    "label": "xtalk",
                    "varname": "fHslider6",
                    "shortname": "xtalk",
                    "address": "/tape/xtalk",
                    "index": 8344,
                    "init": 0,
                    "min": 0,
                    "max": 1,
                    "step": 0.001
                }
            ]
        }
    ]
}
