#!/usr/bin/env node
/**
 * Compiles all .dsp files in faust/dsp/ to WebAssembly.
 * Output per synth:
 *   faust/wasm/{name}/dsp-module.wasm
 *   faust/wasm/{name}/dsp-meta.json
 *   faust/wasm/{name}/mixer-module.wasm  (poly only)
 *   faust/wasm/{name}/index.ts           (generated, imports WASM via new URL)
 *
 * Usage:
 *   npm run faust:compile             -- compile all .dsp files as polyphonic synths
 *   npm run faust:compile -- --mono   -- compile all as monophonic
 */
import faust2wasmFiles from '@grame/faustwasm/src/faust2wasmFiles.js';
import { readdirSync, existsSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dspDir = join(__dirname, 'dsp');
const wasmDir = join(__dirname, 'wasm');

const poly = !process.argv.includes('--mono');

const files = readdirSync(dspDir).filter(f => f.endsWith('.dsp'));
if (!files.length) {
    console.log('No .dsp files found in faust/dsp/');
    process.exit(0);
}

for (const file of files) {
    const name = file.replace('.dsp', '');
    const inputFile = join(dspDir, file);
    const outputDir = join(wasmDir, name);
    if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });
    console.log(`\nCompiling ${name} (${poly ? 'polyphonic' : 'monophonic'})...`);
    try {
        const { dspMeta } = await faust2wasmFiles(inputFile, outputDir, [], poly);
        writeIndexTs(outputDir, dspMeta, poly);
        console.log(`✓ ${name} → wasm/${name}/`);
    } catch (e) {
        console.error(`✗ ${name}: ${e.message}`);
    }
}

function writeIndexTs(outputDir, meta, poly) {
    const mixerLine = poly
        ? `export const mixerUrl = new URL('./mixer-module.wasm', import.meta.url)\n`
        : '';
    const content = `// Generated by faust/compile.mjs — do not edit
export const dspUrl = new URL('./dsp-module.wasm', import.meta.url)
${mixerLine}export const meta = ${JSON.stringify(meta, null, 4)}
`;
    writeFileSync(join(outputDir, 'index.ts'), content);
}
